apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfoservice-data-syfosmregister
  namespace: default
  labels:
    team: {{team}}
spec:
  image: "docker.pkg.github.com/navikt/syfoservice-data-syfosmregister:{{tag}}"
  replicas:
    min: 1
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/prod/srvsyfoservice-dat
        mountPath: /secrets/serviceuser
      - kvPath: kv/prod/fss/syfoservice-data-syfosmregister/default
        mountPath: /secrets/credentials
  webproxy: true
  ingresses:
    - "https://syfoservice-data-syfosmregister.nais.adeo.no"
  env:
    - name: DATABASE_URL
      value: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=a01dbfl030.adeo.no)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=SYFOSYKETILFELLEP)(INSTANCE_NAME=ccpf01)(UR=A)(SERVER=DEDICATED)))